/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountControl: typeof import('./src/components/setup/accountControl.vue')['default']
    AppBar: typeof import('./src/components/appBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BranchControl: typeof import('./src/components/setup/branchControl.vue')['default']
    EditAccount: typeof import('./src/components/setup/editAccount.vue')['default']
    EditRole: typeof import('./src/components/setup/editRole.vue')['default']
    HakTable: typeof import('./src/components/setup/hakTable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InventControl: typeof import('./src/components/setup/inventControl.vue')['default']
    LoginForm: typeof import('./src/components/loginForm.vue')['default']
    MenuControl: typeof import('./src/components/setup/menuControl.vue')['default']
    NewAccount: typeof import('./src/components/setup/newAccount.vue')['default']
    NewRole: typeof import('./src/components/setup/newRole.vue')['default']
    ProfileControl: typeof import('./src/components/setup/profileControl.vue')['default']
    RegisterForm: typeof import('./src/components/registerForm.vue')['default']
    RoleControl: typeof import('./src/components/setup/roleControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetProfil: typeof import('./src/components/setup/setProfil.vue')['default']
  }
}
