/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/cashier': RouteRecordInfo<'/admin/cashier', '/admin/cashier', Record<never, never>, Record<never, never>>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/inventoryControl': RouteRecordInfo<'/admin/inventoryControl', '/admin/inventoryControl', Record<never, never>, Record<never, never>>,
    '/admin/kitchenDashboard': RouteRecordInfo<'/admin/kitchenDashboard', '/admin/kitchenDashboard', Record<never, never>, Record<never, never>>,
    '/admin/report': RouteRecordInfo<'/admin/report', '/admin/report', Record<never, never>, Record<never, never>>,
  }
}
